---
title: "Post mid semester"
author: "Hannah Possehl and Gus Christensen"
date: "2023-03-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In total using 193 countries.
### Loading Data
```{r echo = FALSE}
esg_data = readxl::read_excel("C:/Users/hanna/OneDrive/Documents/R/Countries_Environment_Social_and_Governance_(ESG)_Data.xlsx", na = "..")
# above data last updated Feb. 9th 2023
# no Kosovo, Palestine, Taiwan, Vatican City
cor_years = esg_data[,c(1,3,12:37)]
rev = cor_years[, c(1,2,ncol(cor_years):3)]
head(rev)
colnames(rev) = c("Country.Name", "Category", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015")
head(rev)
regressors = rev
```


```{r, include = FALSE}
esg_data = data.frame(esg_data)
sue_data = readxl::read_excel("C:/Users/hanna/OneDrive/Documents/R/Sustainable_Energy_for_All.xlsx", col_names = c("Country.Name", "Country.code", "Time", "Time.code", "ACCESS.CFT.TOT", "ACCESS.ELECTRICITY.RURAL", "ACCESS.ELECTRICITY.TOT", "ACCESS.ELECTRICITY.URBAN", "PRIMARY.ENERGY.INTENSITY", "REN.ELECTRICITY.OUTPUT", "SHARE.RE.IN.ELECTRICITY", "RE.CONSUMPTION", "SHARE.TOTAL.RE.IN.TFEC", "TOTAL.ELECTRICITY.OUTPUT", "TOTAL.FINAL.ENERGY.CONSUM]"), col_types = c("text", "text", "numeric", "text", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric", "numeric"))
# has only 195 countries does not have data for Palestine and Vatican City
sefa_data = data.frame(sue_data)
sefa = sefa_data[2:6999,]
perc = !is.na(sefa$SHARE.RE.IN.ELECTRICITY)
nonna = sefa[perc,]
Y = data.frame(nonna$Country.Name, nonna$Time, nonna$SHARE.RE.IN.ELECTRICITY)
#temp = tibble::rownames_to_column(nonna, "Time")
#head(temp)
```

### Combining the two datasets
```{r}
library(reshape)
library(reshape2)
head(nonna)
colnames(nonna)
cast_data = melt(nonna[,c(1,3,5:15)], id = c("Country.Name", "Time"), variable.name="Category")
head(cast_data)
```

```{r}
c_data = dcast(cast_data,Country.Name+Category ~ Time, value.var = "value")
head(c_data)
```
```{r}
regressors_join = rbind(regressors, c_data)
head(regressors_join)
tail(regressors_join)
```

### Checking for NA values
```{r}
years = c('1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015')
na_by_years = c()
for (year in years){
  na_by_years = append(na_by_years, sum(is.na(regressors_join[,year])))
}
na_by_years
```
```{r}
library(dplyr)
rowsums = rowSums(is.na(regressors_join))
#rowsums[rowsums>=10]
empty_rows = which(rowsums==26)
empty_rows
sum(is.na(regressors_join))
 empty_data = regressors_join[empty_rows,]
regressors_join[empty_rows,]
n_distinct(regressors_join[empty_rows,]$Category)
unique(regressors_join[empty_rows,]$Category)
n_distinct(regressors_join[empty_rows,]$Country.Name)
unique(regressors_join[empty_rows,]$Country.Name)
```

```{r}
library(tidyr)

as.data.frame(table(empty_data$Country.Name))
as.data.frame(table(empty_data$Category))
```

### Description of Feature variables
```{r pressure, echo=FALSE}
library(summarytools)

descr(regressors_join[,3:28])
```


### Creating Country Clusters
```{r}
library(ggplot2)
gdp_pop_data <- readxl::read_excel("gdp_pop_data.xlsx", col_types = c("text", "text", "text", "text", "numeric", "numeric", "numeric"))
colnames(gdp_pop_data) <- c("Country.Name", "Country.Code", "Series.Name", "Series.Code", "2005", "2010", "2015")
head(gdp_pop_data)
gdp = gdp_pop_data[gdp_pop_data$Series.Name == "GDP (current US$)",'2005']
pop = gdp_pop_data[gdp_pop_data$Series.Name == "Population, total",'2005']
print(gdp[1:193,])
print(pop[1:193,])
gdp_data = gdp[1:193,]
pop_data = pop[1:193,]
gdp_pop = data.frame(gdp_data, pop_data)
head(gdp_pop)
#plot(gdp_data[,'2005'],pop_data[,'2005'])
ggplot(gdp_pop, aes(X2005,X2005.1)) +
  geom_point()
```
###Plot for 2005
```{r}
library(ggplot2)
gdp_pop_data <- readxl::read_excel("gdp_pop_data.xlsx", col_types = c("text", "text", "text", "text", "numeric", "numeric", "numeric"))
colnames(gdp_pop_data) <- c("Country.Name", "Country.Code", "Series.Name", "Series.Code", "2005", "2010", "2015")
head(gdp_pop_data)
gdp_2005 = gdp_pop_data[gdp_pop_data$Series.Name == "GDP (current US$)",'2005']
pop_2005 = gdp_pop_data[gdp_pop_data$Series.Name == "Population, total",'2005']
# print(gdp[1:193,])
# print(pop[1:193,])
gdp_data_2005 = gdp_2005[1:193,]
pop_data_2005 = pop_2005[1:193,]
gdp_pop_2005 = data.frame(gdp_data_2005, pop_data_2005)
# head(gdp_pop)
#plot(gdp_data[,'2005'],pop_data[,'2005'])
#Divided by Mean Standardization
gdp_pop_2005$X2005 <- gdp_pop_2005$X2005 / mean(gdp_pop_2005$X2005, na.rm = TRUE)
gdp_pop_2005$X2005.1 <- gdp_pop_2005$X2005.1 / mean(gdp_pop_2005$X2005.1, na.rm = TRUE)
#Plot of dividing by mean
ggplot(gdp_pop_2005, aes(X2005,X2005.1)) +
  geom_point() +
  ggtitle("Population v. GDP (2005)") +
  xlab("Population")+
  ylab("GDP")
#Standardizing with mean = 0 and sd = 1
gdp_pop_2005_s <- gdp_pop_2005 %>% mutate_at(c('X2005', 'X2005.1'), ~(scale(.) %>% as.vector))
ggplot(gdp_pop_2005_s, aes(X2005,X2005.1)) +
  geom_point() +
  ggtitle("Population v. GDP (2005)") +
  xlab("Population")+
  ylab("GDP")
```

###Plot for 2010
```{r}
library(ggplot2)
gdp_pop_data <- readxl::read_excel("gdp_pop_data.xlsx", col_types = c("text", "text", "text", "text", "numeric", "numeric", "numeric"))
colnames(gdp_pop_data) <- c("Country.Name", "Country.Code", "Series.Name", "Series.Code", "2005", "2010", "2015")
head(gdp_pop_data)
gdp_2010 = gdp_pop_data[gdp_pop_data$Series.Name == "GDP (current US$)",'2010']
pop_2010 = gdp_pop_data[gdp_pop_data$Series.Name == "Population, total",'2010']
# print(gdp[1:193,])
# print(pop[1:193,])
gdp_data_2010 = gdp_2010[1:193,]
pop_data_2010 = pop_2010[1:193,]
gdp_pop_2010 = data.frame(gdp_data_2010, pop_data_2010)
# head(gdp_pop)
#plot(gdp_data[,'2005'],pop_data[,'2005'])
#Standardizing by dividing by mean
gdp_pop_2010$X2010 <- gdp_pop_2010$X2010 / mean(gdp_pop_2010$X2010, na.rm = TRUE)
gdp_pop_2010$X2010.1 <- gdp_pop_2010$X2010.1 / mean(gdp_pop_2010$X2010.1, na.rm = TRUE)
#Plot
ggplot(gdp_pop_2010, aes(X2010,X2010.1)) +
  geom_point() +
  ggtitle("Population v. GDP (2010)") +
  xlab("Population")+
  ylab("GDP")
#Standardizing with mean = 0 and sd = 1
gdp_pop_2010_s <- gdp_pop_2010 %>% mutate_at(c('X2010', 'X2010.1'), ~(scale(.) %>% as.vector))
ggplot(gdp_pop_2010_s, aes(X2010,X2010.1)) +
  geom_point() +
  ggtitle("Population v. GDP (2010)") +
  xlab("Population")+
  ylab("GDP")
```

###Plot for 2015
```{r}
library(ggplot2)
gdp_pop_data <- readxl::read_excel("gdp_pop_data.xlsx", col_types = c("text", "text", "text", "text", "numeric", "numeric", "numeric"))
colnames(gdp_pop_data) <- c("Country.Name", "Country.Code", "Series.Name", "Series.Code", "2005", "2010", "2015")
head(gdp_pop_data)
gdp_2015 = gdp_pop_data[gdp_pop_data$Series.Name == "GDP (current US$)",'2015']
pop_2015 = gdp_pop_data[gdp_pop_data$Series.Name == "Population, total",'2015']
# print(gdp[1:193,])
# print(pop[1:193,])
gdp_data_2015 = gdp_2015[1:193,]
pop_data_2015 = pop_2015[1:193,]
gdp_pop_2015 = data.frame(gdp_data_2015, pop_data_2015)
# head(gdp_pop)
#plot(gdp_data[,'2005'],pop_data[,'2005'])
#Standardizing by dividing by mean
gdp_pop_2015$X2015 <- gdp_pop_2015$X2015 / mean(gdp_pop_2015$X2015, na.rm = TRUE)
gdp_pop_2015$X2015.1 <- gdp_pop_2015$X2015.1 / mean(gdp_pop_2015$X2015.1, na.rm = TRUE)
#Plot
ggplot(gdp_pop_2015, aes(X2015,X2015.1)) +
  geom_point() +
  ggtitle("Population v. GDP (2015)") +
  xlab("Population")+
  ylab("GDP")
#Standardizing with mean = 0 and sd = 1
gdp_pop_2015_s <- gdp_pop_2015 %>% mutate_at(c('X2015', 'X2015.1'), ~(scale(.) %>% as.vector))
ggplot(gdp_pop_2015_s, aes(X2015,X2015.1)) +
  geom_point() +
  ggtitle("Population v. GDP (2015)") +
  xlab("Population")+
  ylab("GDP")
```



## Outlier Detection

```{r}
agland = regressors_join[regressors_join$Category == "Agricultural land (% of land area)",]
countries = agland$Country.Name
num_countries = length(t(agland[,"Country.Name"]))
outliers = data.frame(ncol = num_countries, nrows = 0)
colnames(outliers) = agland[,"Country.Name"]
sum = 0
outliers_q = data.frame(ncol = num_countries, nrows = 0)
colnames(outliers_q) = agland[,"Country.Name"]
sum_q = 0

for (country in countries){
  x = unlist(agland[agland$Country.Name == country,], use.names = FALSE)
  X = as.numeric(x[3:28])
  #print(median(X))
  ## MAD method, Hampler Filter
  mad = median(abs((X - median(X))))
  lower_bound = median(X) - 3* mad
  upper_bound = median(X) + 3* mad
  outliers[,country] = t(which(X < lower_bound | X > upper_bound))
  typeof(outliers)
  sum = sum + length(outliers[,country])
  #print(outliers[,country])
  #print(country)
  #print(length(outliers[,country]))
  ## IQR
  quantiles = quantile(X, na.rm = TRUE)
  first_q = quantiles["25%"]
  third_q = quantiles["75%"]
  diff_q = third_q - first_q
  upper_bound_q = third_q + 1.5*diff_q
  lower_bound_q = first_q - 1.5*diff_q
  outliers_q[,country] = t(which(X < lower_bound_q | X > upper_bound_q))
  sum_q = sum_q + length(outliers_q[,country])
 
}
print(sum)
print(sum_q)
#head(agland)
#mad = median(abs(x - median(x)))
#lower_bound = median() - 3* mad()
#upper_bound = median() + 3* mad()

```

MAD:674 outliers, out of 5,018 total data points.
IQR: 287 outliers out ot 5,018

```{r}

```
